version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '02:00'
      timezone: 'Asia/Seoul'
    open-pull-requests-limit: 2
    assignees:
      - 'herokwon'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
      timezone: 'Asia/Seoul'
    open-pull-requests-limit: 5
    assignees:
      - 'herokwon'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    ignore:
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: '*svelte*'
        update-types: ['version-update:semver-major']
      - dependency-name: '*tailwindcss*'
        update-types: ['version-update:semver-major']
      - dependency-name: '*eslint*'
        update-types: ['version-update:semver-major']
      - dependency-name: '*prettier*'
        update-types: ['version-update:semver-major']
      - dependency-name: '*vite*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'wrangler'
        update-types: ['version-update:semver-major']
    groups:
      npm-production:
        dependency-type: production
        update-types:
          - minor
          - patch
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
